export const englishTranslation = {
  "browser-video-unsupported": "Sorry, your browser doesn't support embedded videos.",
  "find-company-to-fitting-needs": "Find the establishment which will fit your needs.",
  "search": "Search",
  "an-issue": "An issue ?",
  "what-are-your-needs": "What are you looking for ?",
  "where": "Where ?",
  "trouble-a-lordre-public": "Trouble à l'ordre public",
  "you-establishment-owner": "Are you an establishment owner ?",
  "boost-your-reservations": "Boost your reservations by adding your establishment",
  "add-your-establishment": "Add your establishment",
  "account-created": "Account created",
  "account-created-information": "Your account has been created.\n" +
      "                        You will receive an email to validate your account.\n" +
      "                        Click on the link to validate your account.",
  "back-to-home": "Back to home",
  "update": "Update",
  "remove": "Remove",
  "no-availability": "No availability",
  "pick-service-and-book": "Choose a service and book a disturbance",
  "comments": "Comments",
  "comment": "Comment",
  "book-disturbance": "Book a disturbance",
  "company-name": "Company name",
  "description": "Description",
  "address": "Address",
  "postal-code": "Postal Code",
  "city": "City",
  "country": "Country",
  "categories": "Categories",
  "fill-all-fields": "Please fill all the fields",
  "company-creation-error": "Error during the establishment creation",
  "service-creation-error": "Error during the service creation",
  "rate-creation-error": "Error during the rate creation",
  "forgotten-password": "Forgot your password?",
  "enter-email-forgotten-password": "Enter your email and we will send you a link to reset your password.",
  "email": "Email",
  "send-recovery-link": "Send a recovery link",
  "wrong-log-info": "Wrong login information",
  "catch-phrase-1": "You miss the riots ?",
  "catch-phrase-2": "We've got the",
  "catch-phrase-3": " solution.",
  "password": "Password",
  "login": "Login",
  "no-account-yet": "No account yet ?",
  "register": "Register",
  "thank-for-trust": "Thank you for your trust !",
  "your-appointment": "Your appointment with",
  "at": "at",
  "with": "with",
  "is-planned-on": "is planned on",
  "your-appointment-at": "Your appointment with",
  "see-my-calendar": "See my calendar",
  "confirm": "Confirm",
  "choose-a": "Choose a",
  "firstname": "Firstname",
  "name": "Name",
  "confirm-password": "Confirm password",
  "reset-password": "Reset password",
  "hour": "Hour",
  "duration": "Duration",
  "duration-in-minutes": "Duration (in minutes)",
  "the-client": "The client",
  "the-trouble-maker": "The trouble maker",
  "add-note": "Add a rate",
  "new-password-and-confirm-it": "Enter your new password and confirm it.",
  "password-regex": "Passwords must match and be at least 8 characters with number & special",
  "search-results-for": "Results for",
  "see-more": "See more",
  "no-result": "No result found",
  "title": "Title",
  "price": "Price",
  "create":"Create",
  "appointment-with":"appointment with",
  "accept":"Accept",
  "refuse":"Refuse",
  "no-invitation":"No invitation yet",
  "become-trouble-maker":"Become trouble maker",
  "stop-being-trouble-maker":"Stop being trouble maker",
  "validate-account":"Validate your account",
  "validate-account-click":"Click the button below to validate your account.",
}