export const frenchTranslation = {
  "browser-video-unsupported": "Votre navigateur ne supporte pas les vidéos.",
  "find-company-to-fit-your-needs": "Trouvez l'établissement qui correspond à vos besoins.",
  "search": "Rechercher",
  "an-issue": "Un problème ?",
  "where": "Où ça ?",
  "trouble-a-lordre-public": "Trouble à l'ordre public",
  "you-establishment-owner": "Vous êtes propriétaires",
  "of-an-establishment": "d'un établissement",
  "boost-your-reservations": "Augmentez vos réserverations en ajoutant votre établissement",
  "add-your-establishment": "Ajoutez votre établissement",
  "account-created": "Compte créé",
  "account-created-information": "Votre compte a été créé avec succès.\n" +
      "                        Vous recevrez un email pour valider votre compte.\n" +
      "                        Cliquez sur le lien dans l'email pour valider votre compte.",
  "back-to-home": "Retour à l'accueil",
  "update": "Modifier",
  "remove": "Supprimer",
  "no-availability": "Aucune disponibilité pour le moment",
  "pick-service-and-book": "Choisissez votre service et commandez un p'tit trouble",
  "comments": "Commentaires",
  "comment": "Commentaire",
  "book-disturbance": "Commandez un trouble",
  "company-name": "Nom de l'entreprise",
  "description": "Description",
  "address": "Adresse",
  "postal-code": "Code Postal",
  "city": "Ville",
  "country": "Pays",
  "categories": "Catégories",
  "fill-all-fields": "Veuillez remplir tous les champs",
  "company-creation-error": "Erreur lors de la création de l'établissement",
  "service-creation-error": "Erreur lors de la création du service",
  "rate-creation-error": "Erreur lors de la création de la note",
  "forgotten-password": "Mot de passe oublié ?",
  "enter-email-forgotten-password": "Renseignez votre email et nous vous enverrons un lien de récupération.",
  "email": "Email",
  "send-recovery-link": "Envoyer un lien de réinitialisation",
  "wrong-log-info": "Vos identifiants sont incorrects.",
  "catch-phrase-1": "Les émeutes vous manquent ?",
  "catch-phrase-2": "On a la",
  "catch-phrase-3": " solution.",
  "password": "Mot de passe",
  "login": "Se connecter",
  "no-account-yet": "Pas encore de compte ?",
  "register": "S'inscrire",
  "thank-for-trust": "Merci pour votre confiance !",
  "your-appointment": "Votre rendez-vous avec",
  "at": "chez",
  "with": "avec",
  "is-planned-on": "est prévue le",
  "your-appointment-at": "Votre rendez-vous avec",
  "see-my-calendar": "Voir mon calendrier",
  "confirm": "Confirmer",
  "choose-a": "Choisir une",
  "firstname": "Prénom",
  "name": "Nom",
  "confirm-password": "Confirmer le mot de passe",
  "reset-password": "Réinitialiser le mot de passe",
  "hour": "Heure",
  "duration": "Durée",
  "duration-in-minutes": "Durée (en minutes)",
  "the-client": "Le client",
  "the-trouble-maker": "Le fauteur de trouble",
  "add-note": "Ajouter une note",
  "new-password-and-confirm-it": "Entrez un nouveau mot de passe et confirmez-le.",
  "password-regex": "Les mots de passe doivent être identiques, faire 8 caractères minimum dont un chiffre et un caractère spécial",
  "search-results-for": "Résultats de recherche pour",
  "see-more": "Voir plus",
  "no-result": "Aucun résultat trouvé",
  "title": "Titre",
  "price": "Prix",
  "create":"Créer",
  "appointment-with":"rendez-vous avec",
  "accept":"Accepter",
  "refuse":"Refuser",
  "no-invitation":"Aucune invitation pour le moment",
  "become-trouble-maker":"Devenir fauteur de trouble",
  "stop-being-trouble-maker":"Ne plus être fauteur de trouble",
  "validate-account":"Valider votre compte",
  "validate-account-click":"Cliquez sur ce bouton pour valider votre compte.",
}