

api:
  type: php:8.3
  source:
    root: api
  dependencies:
    php:
      composer/composer: "^2"

  runtime:
    extensions:
      - apcu
      - ctype
      - iconv
      - mbstring
      - pdo_pgsql
      - sodium
      - xsl


  variables:
    php:
      opcache.preload: config/preload.php
  build:
    flavor: none

  disk: 1024

  web:
    locations:
      "/":
        root: "public"
        passthru: '/index.php'
        index:
          - index.php
        scripts: true
        allow: true
        headers:
          Access-Control-Allow-Origin: "*"

  mounts:
    "/var": { source: local, source_path: var }

  relationships:
    database: "database:postgresql"

  hooks:
    build: |
      cp .env.example .env
      set -x -e
      curl -s https://get.symfony.com/cloud/configurator | bash
      symfony-build
      bin/console lexik:jwt:generate-keypair --overwrite
    deploy: |
      set -x -e
      symfony-deploy
