name: CI API

on:
  push:
    branches:
      - main
      - feat/*
  pull_request:
    branches:
      - main
      - feat/*

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Run Tests
        run: |
          docker compose -f compose.yaml -f compose.override.yaml up -d
          docker compose exec -T php composer install
          docker compose exec -T php bin/phpunit
          docker compose exec -T php bin/console -e test doctrine:schema:validate
        continue-on-error: true  # Continue to the next step even if tests fail

      - name: Stop services
        run: docker compose down

  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
